<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyTitle>WARP Генератор</AssemblyTitle>
    <AssemblyDescription>WARP Генератор конфигураций AmneziaWG, WireSock и Clash</AssemblyDescription>
    <Description>WARP Генератор конфигураций AmneziaWG, WireSock и Clash</Description>
    <Company>XoXoТач</Company>
    <Product>WARP Генератор</Product>
    <Copyright>Copyright © 2026 XoXoТач</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*" />
    <Resource Include="icon.ico" />
    <Resource Include="icon_green.ico" />
  </ItemGroup>

</Project>
